version: '3.1'

services:
  postgres:
    container_name: rockelivery_postgres
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      